name: gh-pages

on:
  push:
  workflow_dispatch:

# https://docs.github.com/zh/actions/using-jobs/assigning-permissions-to-jobs
permissions: write-all

defaults:
  run:
    shell: bash

env:
  APP_NAME: stellarium-web-engine
  PUBLICPATH: /stellarium-web-engine

jobs:
  build_and_deploy:
    name: Build depoly files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Initialization
        run: |
          # fix the input device is not a TTY
          sed -i "s/docker run -it/docker run/" Makefile
          # fix EACCES: permission denied, open '/app/yarn-error.log' due to the 'USER node' in Dockerfile
          ls -la .
          find . -type d -exec sudo chmod 777 {} \;
          ls -la .
          make setup
          make update-engine
        working-directory: apps/web-frontend
      - name: Building ...
        run: |
          NODE_OPTIONS=--openssl-legacy-provider VUE_APP_PUBLIC_PATH=${{env.PUBLICPATH}} npm run build
          pwd && ls -la dist
          # fix https://github.com/peaceiris/actions-gh-pages/issues/892#issuecomment-1870004268 temporary
          touch dist/.nojekyll
          # cp ../test-skydata dist/skydata, see also Makefile
          cp -r ../test-skydata dist/skydata
        working-directory: apps/web-frontend
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/web-frontend/dist
        
      - name: Building default static files ...
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          NODE_OPTIONS=--openssl-legacy-provider npm run build
          cp -r ../test-skydata dist/skydata
          7z a -tzip ${{env.APP_NAME}}.zip -r ./dist/*
        working-directory: apps/web-frontend
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: apps/web-frontend/${{env.APP_NAME}}.zip